name                = "augustduarte"
compatibility_date  = "2026-07-06"
main                = "worker.js"

[assets]
directory = "public"

[[r2_buckets]]
binding     = "FILES"
bucket_name = "augustduarte-files"
